"""empty message

Revision ID: 4f67b037e390
Revises: c44bc2c83c23
Create Date: 2021-11-13 15:09:10.282858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f67b037e390'
down_revision = 'c44bc2c83c23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_activity', sa.DateTime(), nullable=True))
    op.drop_column('user', 'last_login')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('user', 'last_activity')
    # ### end Alembic commands ###
