"""Add some restrictions

Revision ID: 638a188c9ee7
Revises: 4f67b037e390
Create Date: 2021-11-19 00:54:33.409775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638a188c9ee7'
down_revision = '4f67b037e390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('age_restriction', 'title',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.create_unique_constraint(None, 'age_restriction', ['title'])
    op.alter_column('country', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('country', 'abbreviation',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.create_unique_constraint(None, 'country', ['title'])
    op.create_unique_constraint(None, 'country', ['abbreviation'])
    op.alter_column('director', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('director', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('genre', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_unique_constraint(None, 'genre', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genre', type_='unique')
    op.alter_column('genre', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('director', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('director', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(None, 'country', type_='unique')
    op.drop_constraint(None, 'country', type_='unique')
    op.alter_column('country', 'abbreviation',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    op.alter_column('country', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(None, 'age_restriction', type_='unique')
    op.alter_column('age_restriction', 'title',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    # ### end Alembic commands ###
